name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MyRecipeBook

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore MyRecipeBook.slnx

      - name: Build
        run: dotnet build MyRecipeBook.slnx --no-restore
      
      - name: Test with Coverage
        run: >
          dotnet test MyRecipeBook.slnx 
          --no-build 
          --settings cover.runsettings
          --collect:"XPlat Code Coverage"
          --logger "trx"
          --results-directory TestResults
      
      - name: Upload test results and coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-and-coverage
          path: MyRecipeBook/TestResults/**
       

